#!/usr/bin/env python3
'''
Author: Yuankai He
Correspondence: yh464@cam.ac.uk
Version 1: 2025-05-27

A script to batch run GWAS by GENESIS

Requires following inputs: 
    phenotype file in FID IID *** format
    covariants files in FID IID *** format
    PLINK bed binaries, needs all autosomes concatenated into one file
'''

from _utils import logger
log = logger.logger()
from hashlib import sha256
import os

def main(args):
  # array submitter
  from _utils.slurm import array_submitter
  jobname = sha256(repr(args).encode()).hexdigest()[:6]
  grm_submitter = array_submitter(name = f'grm_pcrelate_{jobname}', timeout = 360, n_cpu = 4, env = 'gentoolsr')
  submitter = array_submitter(name = f'gwa_genesis_{jobname}', timeout = 240, n_cpu = int(args.n_threads/3), 
    env = 'gentoolsr', dependency = [grm_submitter])
  
  # compile SNP list
  tmpdir = os.path.realpath('/home/yh464/rds/rds-rb643-ukbiobank2/Data_Users/yh464/temp/_snp_list')
  os.makedirs(tmpdir, exist_ok = True)
  if len(args.extract) > 0:
    if os.path.isfile(args.extract[0]): extract = f'--extract {os.path.realpath(args.extract[0])} '
    else:
      snp_file = f'{tmpdir}/{sha256(" ".join(args.extract).encode()).hexdigest()[:6]}.txt'
      with open(snp_file, 'w') as f:
        for snp in args.extract:
          print(snp, file = f)
      extract = f'--extract {snp_file}'
  else: extract = ''

  # check for GRM generated by PC-RELATE
  if not os.path.isfile(f'{args.bed}.pcrelate.rdata'):
    if not os.path.isfile(f'{args.bed}.bed'): raise FileNotFoundError(f'PLINK bed file {args.bed}.bed not found')
    Warning('No GRM found, generating GRM by PC-RELATE')
    grm_submitter.add(f'Rscript grm_pcrelate.r -i {args.bed}')
    grm_submitter.submit()

  for g in args.pheno:
    # check phenotype file
    pheno_file = f'{args._in}/{g}'
    if pheno_file[-4:] not in ['.txt','.tsv','.csv']: pheno_file += '.txt'
    if not os.path.isfile(pheno_file): raise FileNotFoundError(f'Phenotype file {pheno_file} not found')
    hdr = open(pheno_file).readline().strip().split()
    if hdr[0] != 'FID' or hdr[1] != 'IID':
      raise ValueError('Phenotype file should be in the format: FID IID *pheno')

    # output directory
    prefix = g.replace('.txt','').replace('.tsv','').replace('.csv','')
    outdir = f'{args.out}/{prefix}'
    if os.path.isdir(outdir):
      tmp = input(f'Found existing output directory, please check or specify new output directory: \n[{outdir}]')
      if len(tmp) == 0: pass
      elif tmp.find('/') == -1: outdir = f'{outdir}{tmp}'
      else: outdir = tmp
    if not os.path.isdir(outdir): os.system(f'mkdir -p {outdir}')
    log.log(f'GWAS output will be saved to {outdir}')

    # run GENESIS
    for p in hdr[2:]:
      out_file = f'{outdir}/{p}.fastGWA'
      if os.path.isfile(out_file) and not args.force: continue
      cmd = ['Rscript', 'gwa_genesis.r', p, '-i', pheno_file, '-o', outdir, '-b', args.bed, '--dcov', args.dcov, 
             '--qcov', args.qcov, '--snp', args.snp,'--maf', str(args.maf), '--n_threads',str(args.n_threads)]
      if args.extract != [] and len(args.extract) > 0: cmd.append(extract)
      if args.force: cmd.append('-f')
      submitter.add(' '.join(cmd))
  submitter.submit()
  return submitter

if __name__ == '__main__':
  from _utils.slurm import slurm_parser
  parser = slurm_parser(description = 'This script batch runs GWAS by GENESIS')
  parser.add_argument('pheno', help = 'Phenotype group file name, format FID IID ***', nargs = '*')
  parser.add_argument('-i','--in', dest = '_in', help = 'Phenotype directory', default = '../pheno/abcd/')
  parser.add_argument('-o','--out', dest  = 'out', help = 'Output directory', default = '../gwa')
  parser.add_argument('-d','--dcov',dest = 'dcov', help = 'DISCRETE covariance file', default = '../params/abcd_dcov.txt')
  parser.add_argument('-q','--qcov',dest = 'qcov', help = 'QUANTITATIVE covariance file', default = '../params/abcd_qcov.txt')
  parser.add_argument('-b','--bed', help = 'PLINK bed file PREFIX, needs all autosomes',
    default = '/home/yh464/rds/rds-rb643-ukbiobank2/Data_Users/yh464/params/bed_abcd/abcd_eur')
  parser.add_argument('-s','--snp', 
    help = 'SNP information table from larger population as GENESIS is used for small sample size, requires SNP and AF1 columns',
    default = '/home/yh464/rds/rds-rb643-ukbiobank2/Data_Users/yh464/params/ukb_snp_info.txt')
  parser.add_argument('--extract', nargs='*', help = 'SNPs to extract from input files', default = [])
  parser.add_argument('--maf', type = float, default = 0.01, help = 'Minor allele frequency threshold for SNPs')
  parser.add_argument('--n_threads', type = int, default = 8, help = 'Number of threads to use')
  parser.add_argument('-f','--force', dest = 'force', help = 'Force overwrite',
    default = False, action = 'store_true')
  
  args = parser.parse_args()
  import os
  for arg in ['_in','out','dcov','qcov','bed']:
      setattr(args, arg, os.path.realpath(getattr(args, arg)))
  
  from _utils import cmdhistory, logger
  logger.splash(args)
  cmdhistory.log()
  try: main(args)
  except: cmdhistory.errlog()